language: node_js
node_js:
  - "8"
  - "10"

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    - GH_REF="github.com/haganbmj/obs-websocket-js"
    - DEBUG="obs-websocket-js:*"

before_script:
  - npm install json -g
  - bash ./.travis/pre-build.sh
  - npm install

script:
  - npm run build
  - npm test

after_success:
  - bash ./.travis/gh-pages.sh
  - npm run node-coveralls

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
